config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'users/profile', as: 'user_root'
  root "tasks#index", as: 'home_page'
  resources :tasks do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :comments
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :status, inclusion: { in: %w(New Progress Done) },
            presence: true
  # belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # has_many :tasks
  devise :database_authenticatable, :registerable,
         :recoverable,  :validatable

  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @task = Task.find(params[:task_id])
    @comment = @task.comments.create(comment_params)
    redirect_to task_path(@task)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :status)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :admin])
    params.require(:user).permit(:last_name, :first_name, :email, :password, :password_confirmation)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name,:first_name, :admin])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= task.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= task.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [@task, @task.comments.build], local: true do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoList</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container">
    <div class="float-left">
          <span class="navbar-brand d-flex align-items-center">
            <strong>  <%= link_to 'To do List', home_page_path %></strong>
          </span>

    </div>
    <span class="navbar-brand d-flex ">
          <% if user_signed_in? %>
            <span><%= link_to current_user.last_name, user_root_path %></span>
            <span class="btn btn-outline-primary ">
              <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
            </span>
          <% else %>
            <div class="float-right">
              <span class="btn btn-outline-primary ">
                <%= link_to 'Sign in', new_user_session_path %>
              </span>
              <span class="btn btn-outline-primary">
                <%= link_to 'Sign up', new_user_registration_path %>
              </span>
            </div>
          <% end %>
        </span>
  </div>
</div>
<!--<p class="notice"><%#= notice %></p>-->
<!--<p class="alert"><%#= alert %></p>-->
<div class="container mt-10">
  <%= yield %>
</div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task, local: true do |form| %>
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <%= task.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <%= task.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.select :status, ["New", "Progress", "Done"] %>
  </div>
  <div class="form-group">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1 class="text-center">Edit Article</h1>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class=" container">
  <h1 class="text-center">Tasks</h1>
  <div class="container">
    <div class="container mb-3">
      <div class="row">
        <div class="col-sm">
          <h3>Title</h3>
        </div>
        <div class="col-sm">
          <h4>Status</h4>
        </div>
        <div class="col-sm">
          <% if user_signed_in? %>
            <span class="btn btn-outline-primary"> <%= link_to "New task", new_task_path %></span>
          <%end %>
        </div>
      </div>
    </div>
    <% @tasks.each do |task| %>
      <div class="row mb-3">
        <div class="col-sm border mr-1 ml-1">
          <h3><%= task.title %></h3>
        </div>
        <div class="col-sm border mr-1 ml-1">
          <h4><%= task.status %></h4>
        </div>
        <div class="col-sm  mr-1 ml-1">
          <span class="btn btn-outline-primary"> <%= link_to "More", task %></span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1 class="text-center">New Article</h1>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1 class="text-center"><%= @task.title %></h1>
<div class="container mt-3">
  <p class="text-center "><%= @task.description %></p>
  <% if user_signed_in? %>
    <span class="btn btn-outline-primary">
      <%= link_to "Edit", edit_task_path(@task) %>
    </span>
    <% if current_user.admin? %>
      <span class="btn btn-outline-primary">
          <%= link_to "Destroy", task_path(@task),
                      method: :delete,
                      data: { confirm: "Are you sure?" } %>
      </span>
    <% end %>
  <% end %>
</div>

<h2>Comments</h2>
<%= render @task.comments %>

<% if user_signed_in? %>
  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>
<% end %>

app/views/users/profile.html.erb
<h1><span>Здравствуйте, <%= current_user.last_name %></span></h1>